<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class DeleteSeededQuestions extends Command
{
    protected $signature = 'questions:delete-seeded 
                            {--dry-run : Show what would be deleted without actually deleting}
                            {--force : Skip confirmation prompt}';

    protected $description = 'Delete questions generated by the QuestionsTableSeeder';

    public function handle(): int
    {
        $dryRun = $this->option('dry-run');
        $force = $this->option('force');

        $query = DB::table('questions')
            ->whereIn('userID', [1, 2, 3])
            ->whereNotNull('approvedBy')
            ->where('status_id', 2);

        $total = $query->count();
        $subjects = DB::table('questions')
            ->select('subjectID', DB::raw('COUNT(*) as count'))
            ->whereIn('userID', [1, 2, 3])
            ->whereNotNull('approvedBy')
            ->where('status_id', 2)
            ->groupBy('subjectID')
            ->get();

        if ($total === 0) {
            $this->info('No seeded questions found.');
            return 0;
        }

        $this->warn("Found {$total} seeded question(s) across {$subjects->count()} subject(s):");
        $this->table(
            ['Subject ID', 'Question Count'],
            $subjects->map(fn($s) => [$s->subjectID, $s->count])->toArray()
        );

        if ($dryRun) {
            $this->info('Dry run complete. No questions were deleted.');
            return 0;
        }

        if (!$force) {
            if (!$this->confirm("Delete these {$total} questions?")) {
                $this->info('Aborted.');
                return 0;
            }
        }

        DB::table('choices')
            ->whereIn('questionID', $query->pluck('questionID'))
            ->delete();

        $query->delete();

        $this->info("Deleted {$total} seeded questions successfully.");
        return 0;
    }
}
